version: '3.8'

services:
  # Development service
  dev:
    build:
      context: .
      target: builder
    container_name: quiz-app-dev
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    command: npm start

  # Production service
  prod:
    build:
      context: .
    container_name: quiz-app-prod
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production